# Generated by Django 4.2.2 on 2023-07-23 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_fileupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='type',
            field=models.CharField(blank=True, choices=[('departments', 'departments'), ('employees', 'employees')], default='notset', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Admin'), (2, 'company')], default=2, null=True),
        ),
    ]
